# -*- coding: utf-8 -*-
"""Limpeza_Imobiliaria.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176yw5YlA4tyP2_adwjRadxLxjjaUsHNr
"""

import pandas as pd
import numpy as np

# Tabela 1: Imóveis Antigos (Preços em Dólar - Considere 1 USD = 5.00 BRL)
imoveis_antigos = {
    'ref': ['ANT-101', 'ANT-102', 'ANT-103'],
    'descrição': ['Apartamento 2q | Centro | $ 100,000', 'Casa Luxo | Praia | $ 500,000', 'Kitnet | Subúrbio | $ 40,000'],
    'm2': ['80m2', '300 m2', '30m2']
}

# Tabela 2: Imóveis Novos (Preços em Real)
imoveis_novos = {
    'codigo': [201, 202, 203],
    'titulo': ['Apartamento Premium', 'Casa de Campo', 'Galpão Industrial'],
    'local': ['Centro', 'Interior', 'Distrito'],
    'valor_brl': [450000.00, 750000.00, 1200000.00],
    'area': [90, 150, 500]
}

df_antigos = pd.DataFrame(imoveis_antigos)
df_novos = pd.DataFrame(imoveis_novos)


#criação das novas colunas e remoção da antiga
split_info = df_antigos['descrição'].str.split('|', expand=True)

df_antigos['Imóvel'] = split_info[0].str.strip()
df_antigos['Local'] = split_info[1].str.strip()
df_antigos['Valor_usd'] = split_info[2].str.strip()
df_antigos = df_antigos.drop(columns=['descrição'])


#padronização de valores
df_antigos['Valor_usd'] = df_antigos['Valor_usd'].str.replace('$', '').str.replace(',', '')
df_antigos['Valor_usd'] = df_antigos['Valor_usd'].astype(float)
df_antigos['Valor_br'] = df_antigos['Valor_usd'] * 5

#padronização da coluna m2 para área
df_antigos['Área'] = df_antigos['m2'].str.replace('m2', '').str.strip()
df_antigos['Área'] = df_antigos['Área'].astype(float)
df_antigos = df_antigos.drop(columns=['m2'])

df_antigos = df_antigos.rename(columns={'ref': 'Código'})

padrao = {
    'codigo': 'Código',
    'titulo': 'Imóvel',
    'local': 'Local',
    'valor_brl': 'Valor_br',
    'area': 'Área'
}

df_novos = df_novos.rename(columns=padrao)

df_antigos['Código'] = df_antigos['Código'].str.replace('ANT-', '')

display(df_antigos)


df_novos['Valor_usd'] = df_novos['Valor_br'] / 5
df_novos['Valor_usd'] = df_novos['Valor_usd'].round(2)

df_concat = pd.concat([df_antigos, df_novos], axis=0)

df_concat['preco_m2'] = df_concat['Valor_br'] / df_concat['Área']
df_concat['preco_m2'] = df_concat['preco_m2'].round(2)

def definir_perfil(valor):
  if valor > 1000000:
    return 'Investimento Alto'
  if valor > 500000 and valor < 1000000:
    return 'Investimento Médio'
  else:
    return 'Investimento Baixo'

df_concat['perfil_imovel'] = df_concat['Valor_br'].apply(definir_perfil)


df_concat = df_concat.sort_values(by='Valor_br', ascending=False)

df_concat['Media_por_local'] = df_concat.groupby('Local')['Valor_br'].transform('mean').round(2)
df_concat = df_concat.sort_values(by='Valor_br', ascending=False)

display(df_concat)

# Primeiro, criamos um resumo para a segunda aba
df_resumo_perfil = df_concat.groupby('perfil_imovel').agg({
    'Valor_br': 'sum',
    'Área': 'mean'
}).reset_index()

# Agora, usamos o "motor" de escrita
with pd.ExcelWriter('Entrega_Imobiliaria_Final.xlsx') as writer:
    # Aba 1: Dados Completos
    df_concat.to_excel(writer, sheet_name='Base_Geral', index=False)

    # Aba 2: Resumo por Perfil
    df_resumo_perfil.to_excel(writer, sheet_name='Resumo_Investimento', index=False)